In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker

# Reproducibility
np.random.seed(42)
random.seed(42)
Faker.seed(42)

fake = Faker("en_IN")

# Start with 10,000 while testing
N = 10_000

TODAY = pd.Timestamp("2026-08-10")

print("Libraries loaded successfully.")
print("Rows to generate:", N)

Libraries loaded successfully.
Rows to generate: 10000

In [2]:
import numpy as np

print("NumPy working")
print(np.__version__)

NumPy working
2.3.5

In [3]:
import pandas as pd
import numpy as np
import random
from faker import Faker

np.random.seed(42)
random.seed(42)
Faker.seed(42)

fake = Faker("en_IN")

N = 10_000

TODAY = pd.Timestamp("2026-08-10")

print("Libraries loaded successfully.")
print("Rows to generate:", N)

Libraries loaded successfully.
Rows to generate: 10000

In [4]:
customer_id = [
    f"C{str(i).zfill(6)}"
    for i in range(1, N + 1)
]

customer_name = [
    fake.name()
    for _ in range(N)
]

print("Customer IDs and names generated.")
print(customer_id[:5])
print(customer_name[:5])

Customer IDs and names generated.
['C000001', 'C000002', 'C000003', 'C000004', 'C000005']
['Aryan Maharaj', 'Udant Dewan', 'Gagan Sami', 'Ayushman Chander', 'Viraj Tiwari']

In [5]:
gender = np.random.choice(
    ["Male", "Female"],
    N,
    p=[0.55, 0.45]
)

age = np.random.randint(
    18,
    71,
    N
)

senior_citizen = np.where(
    age >= 60,
    "Yes",
    "No"
)

dependents = np.random.choice(
    ["Yes", "No"],
    N,
    p=[0.38, 0.62]
)

print("Demographic data generated.")

Demographic data generated.

In [6]:
locations = {
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Nashik"],
    "Delhi": ["New Delhi", "Delhi"],
    "Karnataka": ["Bengaluru", "Mysuru", "Mangaluru"],
    "Telangana": ["Hyderabad", "Warangal"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara"],
    "West Bengal": ["Kolkata", "Howrah"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur"],
    "Uttar Pradesh": ["Lucknow", "Noida", "Kanpur", "Agra"],
    "Madhya Pradesh": ["Indore", "Bhopal"],
    "Punjab": ["Chandigarh", "Ludhiana", "Amritsar"],
    "Kerala": ["Kochi", "Thiruvananthapuram"]
}

states = list(locations.keys())

state = np.random.choice(
    states,
    N
)

city = [
    random.choice(locations[s])
    for s in state
]

# Realistic-looking Indian PIN codes
pin_code = [
    fake.postcode()
    for _ in range(N)
]

print("Location data generated.")

Location data generated.

In [7]:
customer_segment = np.random.choice(
    [
        "Mass Market",
        "Value",
        "Premium",
        "High Value"
    ],
    N,
    p=[0.40, 0.30, 0.20, 0.10]
)

print("Customer segments generated.")

Customer segments generated.

In [8]:
tenure_months = np.random.randint(
    1,
    73,
    N
)

subscription_type = np.random.choice(
    [
        "Basic",
        "Standard",
        "Premium"
    ],
    N,
    p=[0.40, 0.40, 0.20]
)

contract_type = np.random.choice(
    [
        "Month-to-Month",
        "One Year",
        "Two Year"
    ],
    N,
    p=[0.55, 0.25, 0.20]
)

print("Subscription data generated.")

Subscription data generated.

In [9]:
internet_service = np.random.choice(
    [
        "DSL",
        "Fiber",
        "5G",
        "Cable",
        "None"
    ],
    N,
    p=[0.20, 0.35, 0.20, 0.20, 0.05]
)

tech_support = np.random.choice(
    ["Yes", "No"],
    N,
    p=[0.60, 0.40]
)

print("Internet and technical support data generated.")

Internet and technical support data generated.

In [10]:
monthly_charges = np.zeros(N)

for i in range(N):

    if subscription_type[i] == "Basic":
        charge = np.random.normal(399, 60)

    elif subscription_type[i] == "Standard":
        charge = np.random.normal(699, 90)

    else:
        charge = np.random.normal(1199, 150)

    if internet_service[i] == "Fiber":
        charge += 150

    elif internet_service[i] == "5G":
        charge += 100

    monthly_charges[i] = max(
        charge,
        199
    )

monthly_charges = np.round(
    monthly_charges,
    2
)

discount_percent = np.random.choice(
    [0, 5, 10, 15, 20],
    N,
    p=[0.40, 0.25, 0.20, 0.10, 0.05]
)

total_charges = np.round(
    monthly_charges
    * tenure_months
    * (1 - discount_percent / 100),
    2
)

lifetime_value = np.round(
    total_charges +
    monthly_charges * np.random.uniform(2, 8, N),
    2
)

print("Financial data generated.")

Financial data generated.

In [11]:
payment_method = np.random.choice(
    [
        "UPI",
        "Credit Card",
        "Debit Card",
        "Net Banking",
        "Wallet"
    ],
    N,
    p=[0.30, 0.25, 0.20, 0.15, 0.10]
)

auto_pay = np.random.choice(
    ["Yes", "No"],
    N,
    p=[0.62, 0.38]
)

payment_delay_days = np.random.poisson(
    2,
    N
)

payment_delay_days = np.clip(
    payment_delay_days,
    0,
    30
)

print("Payment data generated.")

Payment data generated.

In [12]:
monthly_data_gb = np.round(
    np.random.gamma(
        shape=4,
        scale=12,
        size=N
    ),
    2
)

avg_call_minutes = np.round(
    np.random.gamma(
        shape=4,
        scale=35,
        size=N
    ),
    0
)

login_frequency = np.random.poisson(
    12,
    N
)

referral_count = np.random.poisson(
    1.2,
    N
)

print("Customer behaviour data generated.")

Customer behaviour data generated.

In [13]:
support_tickets = np.random.poisson(
    2.5,
    N
)

complaints = np.random.poisson(
    0.8,
    N
)

satisfaction_score = np.random.randint(
    1,
    11,
    N
)

nps_score = np.random.randint(
    0,
    11,
    N
)

print("Support and satisfaction data generated.")

Support and satisfaction data generated.

In [14]:
# Last Interaction Date

days_ago = np.random.randint(
    0,
    91,
    N
)

last_interaction_date = (
    TODAY - pd.to_timedelta(
        days_ago,
        unit="D"
    )
)

print("Interaction dates generated.")
print(last_interaction_date[:5])

Interaction dates generated.
DatetimeIndex(['2026-05-28', '2026-07-14', '2026-06-19', '2026-06-04',
               '2026-07-17'],
              dtype='datetime64[ns]', freq=None)

In [15]:
acquisition_channel = np.random.choice(
    [
        "Website",
        "Google Ads",
        "Social Media",
        "Referral",
        "Retail Store",
        "Partner",
        "Telemarketing"
    ],
    N,
    p=[
        0.20,
        0.15,
        0.15,
        0.15,
        0.15,
        0.10,
        0.10
    ]
)

offer_received = np.random.choice(
    [
        "No Offer",
        "10% Discount",
        "20% Discount",
        "Free Upgrade",
        "Extra Data"
    ],
    N,
    p=[
        0.45,
        0.20,
        0.15,
        0.10,
        0.10
    ]
)

print("Marketing data generated.")

Marketing data generated.

In [16]:
churn_score = (
    0.08

    # Contract
    + (contract_type == "Month-to-Month") * 0.16
    - (contract_type == "Two Year") * 0.12

    # Tenure
    + (tenure_months < 12) * 0.12
    - (tenure_months >= 36) * 0.08

    # Customer support
    + (support_tickets >= 5) * 0.10
    + (complaints >= 2) * 0.12

    # Satisfaction
    + (satisfaction_score <= 4) * 0.18
    - (satisfaction_score >= 8) * 0.08

    # Payment
    + (payment_delay_days >= 7) * 0.10
    - (auto_pay == "Yes") * 0.05

    # Engagement
    + (login_frequency <= 3) * 0.10
)

# Random variation
churn_score += np.random.normal(
    0,
    0.05,
    N
)

churn_probability = np.clip(
    churn_score,
    0.02,
    0.90
)

churn = np.random.binomial(
    1,
    churn_probability
)

churn_status = np.where(
    churn == 1,
    "Yes",
    "No"
)

print("Churn status generated.")

Churn status generated.

In [17]:
churn_reason = []

for i in range(N):

    if churn_status[i] == "No":
        reason = "Not Churned"

    elif satisfaction_score[i] <= 3:
        reason = "Poor Service"

    elif complaints[i] >= 2:
        reason = "Customer Support Issues"

    elif payment_delay_days[i] >= 7:
        reason = "Payment Issues"

    elif contract_type[i] == "Month-to-Month":
        reason = "Contract Flexibility"

    else:
        reason = "Competitor Offer"

    churn_reason.append(reason)

print("Churn reasons generated.")

Churn reasons generated.

In [18]:
df = pd.DataFrame({

    "Customer_ID": customer_id,
    "Customer_Name": customer_name,

    "Gender": gender,
    "Age": age,
    "Senior_Citizen": senior_citizen,
    "Dependents": dependents,

    "State": state,
    "City": city,
    "PIN_Code": pin_code,

    "Customer_Segment": customer_segment,

    "Tenure_Months": tenure_months,
    "Subscription_Type": subscription_type,
    "Contract_Type": contract_type,

    "Internet_Service": internet_service,
    "Tech_Support": tech_support,

    "Monthly_Charges": monthly_charges,
    "Total_Charges": total_charges,
    "Discount_Percent": discount_percent,
    "Lifetime_Value": lifetime_value,

    "Payment_Method": payment_method,
    "Auto_Pay": auto_pay,
    "Payment_Delay_Days": payment_delay_days,

    "Monthly_Data_GB": monthly_data_gb,
    "Avg_Call_Minutes": avg_call_minutes,
    "Login_Frequency": login_frequency,

    "Support_Tickets": support_tickets,
    "Complaints": complaints,

    "Satisfaction_Score": satisfaction_score,
    "NPS_Score": nps_score,

    "Referral_Count": referral_count,

    "Acquisition_Channel": acquisition_channel,
    "Offer_Received": offer_received,

    "Last_Interaction_Date": last_interaction_date,

    "Churn": churn_status,
    "Churn_Reason": churn_reason
})

print("Final dataset created!")
print("Shape:", df.shape)

df.head()

Final dataset created!
Shape: (10000, 35)

,Customer_ID,Customer_Name,Gender,Age,Senior_Citizen,Dependents,State,City,PIN_Code,Customer_Segment,...,Support_Tickets,Complaints,Satisfaction_Score,NPS_Score,Referral_Count,Acquisition_Channel,Offer_Received,Last_Interaction_Date,Churn,Churn_Reason
0,C000001,Aryan Maharaj,Male,49,No,Yes,Gujarat,Vadodara,301494,Value,...,3,1,10,7,2,Website,No Offer,2026-05-28,No,Not Churned
1,C000002,Udant Dewan,Female,53,No,No,Karnataka,Bengaluru,298908,High Value,...,3,1,1,8,0,Partner,No Offer,2026-07-14,Yes,Poor Service
2,C000003,Gagan Sami,Female,67,Yes,Yes,Telangana,Hyderabad,966452,Value,...,1,1,6,6,2,Referral,Extra Data,2026-06-19,No,Not Churned
3,C000004,Ayushman Chander,Female,54,No,Yes,Delhi,Delhi,191990,Premium,...,1,0,5,7,0,Retail Store,No Offer,2026-06-04,No,Not Churned
4,C000005,Viraj Tiwari,Male,65,Yes,Yes,West Bengal,Kolkata,133568,Premium,...,3,1,3,5,0,Retail Store,No Offer,2026-07-17,No,Not Churned

In [19]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nChurn Distribution:")
print(df["Churn"].value_counts())

print("\nChurn Percentage:")
print(
    df["Churn"].value_counts(normalize=True) * 100
)

Rows: 10000
Columns: 35

Missing Values:
0

Duplicate Rows:
0

Churn Distribution:
Churn
No     8008
Yes    1992
Name: count, dtype: int64

Churn Percentage:
Churn
No     80.08
Yes    19.92
Name: proportion, dtype: float64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            10000 non-null  object
 1   Customer_Name          10000 non-null  object
 2   Gender                 10000 non-null  object
 3   Age                    10000 non-null  int32
 4   Senior_Citizen         10000 non-null  object
 5   Dependents             10000 non-null  object
 6   State                  10000 non-null  object
 7   City                   10000 non-null  object
 8   PIN_Code               10000 non-null  object
 9   Customer_Segment       10000 non-null  object
 10  Tenure_Months          10000 non-null  int32
 11  Subscription_Type      10000 non-null  object
 12  Contract_Type          10000 non-null  object
 13  Internet_Service       10000 non-null  object
 14  Tech_Support           10000 non-null  object
 15  Monthly_Charges        10000 non-null  float64
 16  Total_Charges          10000 non-null  float64
 17  Discount_Percent       10000 non-null  int64
 18  Lifetime_Value         10000 non-null  float64
 19  Payment_Method         10000 non-null  object
 20  Auto_Pay               10000 non-null  object
 21  Payment_Delay_Days     10000 non-null  int32
 22  Monthly_Data_GB        10000 non-null  float64
 23  Avg_Call_Minutes       10000 non-null  float64
 24  Login_Frequency        10000 non-null  int32
 25  Support_Tickets        10000 non-null  int32
 26  Complaints             10000 non-null  int32
 27  Satisfaction_Score     10000 non-null  int32
 28  NPS_Score              10000 non-null  int32
 29  Referral_Count         10000 non-null  int32
 30  Acquisition_Channel    10000 non-null  object
 31  Offer_Received         10000 non-null  object
 32  Last_Interaction_Date  10000 non-null  datetime64[ns]
 33  Churn                  10000 non-null  object
 34  Churn_Reason           10000 non-null  object
dtypes: datetime64[ns](1), float64(5), int32(9), int64(1), object(19)
memory usage: 2.3+ MB

In [21]:
df.sample(10)

,Customer_ID,Customer_Name,Gender,Age,Senior_Citizen,Dependents,State,City,PIN_Code,Customer_Segment,...,Support_Tickets,Complaints,Satisfaction_Score,NPS_Score,Referral_Count,Acquisition_Channel,Offer_Received,Last_Interaction_Date,Churn,Churn_Reason
2480,C002481,Anjali Korpal,Male,70,Yes,Yes,Uttar Pradesh,Noida,431091,Value,...,3,2,1,7,1,Telemarketing,10% Discount,2026-07-29,Yes,Poor Service
9868,C009869,Zarna Balan,Female,49,No,Yes,Kerala,Thiruvananthapuram,878300,Premium,...,2,2,8,5,0,Social Media,20% Discount,2026-06-04,No,Not Churned
1610,C001611,Kashvi Dugal,Female,35,No,No,Punjab,Amritsar,550652,Mass Market,...,5,2,1,8,2,Referral,Free Upgrade,2026-05-25,No,Not Churned
6483,C006484,Ishani Mital,Male,33,No,No,Uttar Pradesh,Agra,124920,Mass Market,...,3,1,10,8,1,Retail Store,10% Discount,2026-07-23,No,Not Churned
2912,C002913,Ladli Garde,Female,38,No,No,Delhi,New Delhi,090903,Mass Market,...,1,1,4,9,2,Telemarketing,10% Discount,2026-08-04,No,Not Churned
9302,C009303,Nachiket Sura,Female,53,No,No,Uttar Pradesh,Lucknow,737283,Value,...,1,0,10,8,0,Referral,10% Discount,2026-05-30,No,Not Churned
1311,C001312,Aayush Munshi,Female,26,No,No,Madhya Pradesh,Indore,251234,Mass Market,...,1,1,9,4,1,Retail Store,Free Upgrade,2026-08-01,No,Not Churned
5872,C005873,Fitan Deshmukh,Female,68,Yes,Yes,Rajasthan,Udaipur,402308,Value,...,0,0,5,3,2,Google Ads,No Offer,2026-06-10,No,Not Churned
8924,C008925,Kashish Palla,Male,63,Yes,No,Punjab,Chandigarh,975271,Mass Market,...,3,1,4,8,3,Retail Store,No Offer,2026-06-24,No,Not Churned
2708,C002709,Oeshi Mani,Male,53,No,No,Rajasthan,Udaipur,248729,Value,...,3,0,2,6,1,Retail Store,Extra Data,2026-05-25,Yes,Poor Service

In [22]:
df.to_csv(
    "customer_churn_industry_level.csv",
    index=False
)

print("CSV exported successfully!")

CSV exported successfully!